Week3_Simple_Search_Engine/mysearch/myproject/urls.py
from django.conf.urls import url
from django.contrib import admin

from accounts import views as accounts_views
from boards import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^signup/$', accounts_views.signup, name='signup'),
    url(r'^boards/(?P<pk>\d+)/$', views.board_topics, name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'^boards/(?P<cnt>\d+)/details/$', views.get_details, name='get_details'),
    url(r'^admin/', admin.site.urls),
    url(r'^info/(?P<index>\d*)/(?P<tsearch>.*)$',views.info,name='info'),
    url(r'^index/(?P<index>.*)$',views.index,name='index'),
]

Week3_Simple_Search_Engine/mysearch/accounts/models.py
from django.db import models

# Create your models here.

Week3_Simple_Search_Engine/mysearch/boards/models.py
from django.db import models
from django.contrib.auth.models import User

# 在翻译这篇文章的时候，使用的是python 3.6.4， Django 2.0.2
# ForeignKey中有一个on_delete参数

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, models.CASCADE, related_name='topics')
    starter = models.ForeignKey(User, models.CASCADE, related_name='topics')

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, models.CASCADE, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, models.CASCADE, related_name='posts')
    updated_by = models.ForeignKey(User, models.CASCADE, null=True, related_name='+')

class News(models.Model):
    title = models.CharField(max_length=255)
    date = models.CharField(max_length=255)
    contents = models.CharField(max_length=25555)
    cnt = models.IntegerField()

Week3_Simple_Search_Engine/mysearch/accounts/views.py
from django.shortcuts import render

def signup(request):
    return render(request, 'signup.html')

Week3_Simple_Search_Engine/mysearch/boards/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board, Topic, Post,News
import json
import jieba
import re
import time
from random import randint
import random
from django.core import paginator
def home(request):
    boards = Board.objects.all()   
    if request.method == 'POST':
        search = request.POST['search']
        sTime = request.POST.get('startTime','')
        eTime = request.POST.get('endTime','')
        return redirect('info', index=1,tsearch=search+'-'+sTime+'-'+eTime)

        #return render(request,'info.html',context)
        '''
        search = request.POST['search']
        if search is '':
            return render(request, 'home.html', {'boards': boards})              
        f=open("../index.pkl",'r',encoding='utf-8')
        a=json.load(f)
        f.close()
        try:
            ans=a[search]
        except:
            ans=[]
        results=[]
        cntt=0
        for num in ans:
            cntt=cntt+1
            if cntt>15:
                break
            news = News.objects.get(cnt=num)
            results.append(news)
        '''
        '''
        message = request.POST['message']

        user = User.objects.first()  # TODO: 临时使用一个账号作为登录用户

        topic = Topic.objects.create(
            subject=subject,
            board=board,
            starter=user
        )

        post = Post.objects.create(
            message=message,
            topic=topic,
            created_by=user
        )
        '''
        #return render(request, 'result.html', {'search': search,'results': results}) # TODO: redirect to the created topic page
    return render(request, 'home.html', {'boards': boards})

def board_topics(request, pk):
    board = get_object_or_404(Board, pk=pk)
    # 我不懂为什么pk也有用……囧
    return render(request, 'topics.html', {'board': board})

def get_details(request, cnt):
    news = News.objects.get(cnt=cnt)
    nlist=list(jieba.cut(news.title))
    f=open("../index.pkl",'r',encoding='utf-8')
    a=json.load(f)
    f.close()
    recomments=[]
    cntt=0
    for i in nlist:
        try:
            tmp=len(a[i])
            ans=a[i][randint(0,tmp)]
            tmpnews=News.objects.get(cnt=ans)
            if tmpnews.title!=news.title:
                recomments.append(tmpnews)
                cntt=cntt+1
            if cntt>=10:
                break
        except:
            pass
    return render(request, 'details.html', {'news': news,'recomments': recomments})
    #boards = Board.objects.all()
    #return render(request, 'home.html', {'boards': boards})

def new_topic(request, pk):
    board = Board.objects.get(pk=pk)
    if request.method == 'POST':
        subject = request.POST['subject']
        message = request.POST['message']

        user = User.objects.first()  # TODO: 临时使用一个账号作为登录用户

        topic = Topic.objects.create(
            subject=subject,
            board=board,
            starter=user
        )

        post = Post.objects.create(
            message=message,
            topic=topic,
            created_by=user
        )
        return redirect('board_topics', pk=board.pk)  # TODO: redirect to the created topic page
    return render(request, 'new_topic.html', {'board': board})

with open("../index.pkl",'r',encoding='utf-8') as f:
    a=json.load(f)

    
def analyze(t):
    return list(map(int,re.compile('[0-9]+').findall(t)))[:3]

def info(request,index,tsearch):
    tlist=tsearch.split('-')
    # 获取所有的的数据，list是一个列表，包含有所有数据对应的实例对象
    startTime=time.time()

    print(tsearch,tlist)

    search,sTime,eTime = tlist

    global a

    try:
        ans=a[search]
    except:
        ans=[]
    results=[]
    cntt=0
    for num in ans:        
        if cntt>15:
            break
        cntt=cntt+1
        news = News.objects.get(cnt=num)
        results.append(news)
    # 使用Paginator方法返回一个分页的对象
    # 这个对象包括所有数据，分页的情况
    #print(analyze(results[0].date),results[0].date,type(results[0].date),sTime)
    results=sorted(results,key=lambda x:analyze(x.date))
    if sTime:
        sTime=analyze(sTime)
        results=[i for i in results if sTime<=analyze(i.date)]
    if eTime:
        eTime=analyze(eTime)
        results=[i for i in results if eTime>=analyze(i.date)]
    #random.shuffle(results)
    pag = paginator.Paginator(results,5)
    # 使用此判断语句是为了在用户跳转www.xxx.com/info/时也能访问第一页
    if index=='':
        index=1
    # 返回指定（index）页的数据，用于呈现在指定页上
    page = pag.page(index)
    # 构造上下文，以便html文件中能调用对应页的数据
    endTime=time.time()
    time1=str(endTime-startTime)
    print("Time consuming:"+str(endTime-startTime))

    context = {
        'page':page,
        'tsearch':tsearch,
        'search':search,
        'time1':time1,
        'cntt':len(results),
    }

    
    return render(request,'info.html',context)

def index(request,index):

    results=list(News.objects.all())
    num=len(results)
    search=''
    # 使用Paginator方法返回一个分页的对象
    # 这个对象包括所有数据，分页的情况
    random.shuffle(results)
    pag = paginator.Paginator(results,300)
    # 使用此判断语句是为了在用户跳转www.xxx.com/info/时也能访问第一页
    # 返回指定（index）页的数据，用于呈现在指定页上
    if index=='':
        index=1
    if index=='1/':
        index=1
    page = pag.page(index)
    # 构造上下文，以便html文件中能调用对应页的数据
    context = {
        'page':page,
        'search':search,
        'num':num,
    }

    return render(request,'index.html',context)

Week3_Simple_Search_Engine/mysearch/templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}肥宅快乐搜索器{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        span.highlighted {
            color: red;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">首页</a>
      </div>
    </nav>

    <div class="container">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

Week3_Simple_Search_Engine/mysearch/templates/details.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">肥宅快乐搜索器</a></li>
  <li class="breadcrumb-item active">{{ news.title }}</li>
{% endblock %}

{% block content %}
  <div class="mb-4">
  </div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>{{news.title}}</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ news.date }}</td>
      </tr>
      <tr>
        <td>{{ news.contents }}</td>
      </tr>
    </tbody>

  </table>
    <div class="mb-4">
  </div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>相关推荐</th>
        <th>Id</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      {% for news in recomments %}

        <tr>
          <td>
          <a href="{% url 'get_details' news.cnt %}">{{news.title}}</a>
          </td>
          <td>{{ news.cnt }}</td>
          <td>{{ news.date }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Week3_Simple_Search_Engine/mysearch/templates/home.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">肥宅快乐搜索器</li>
{% endblock %}

{% block content %}
<!--
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Board</th>
        <th>Posts</th>
        <th>Topics</th>
        <th>Last Post</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">0</td>
          <td class="align-middle">0</td>
          <td></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>-->
    <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Search</label>
      <input type="text" class="form-control" id="id_subject" name="search">
    </div>
    <div class="form-group">
      <label for="id_start">startTime</label>
      <input type="text" class="form-control" id="id_start" name="startTime">
    </div>
    <div class="form-group">
      <label for="id_end">endTime</label>
      <input type="text" class="form-control" id="id_start" name="endTime">
    </div>
    <button type="submit" class="btn btn-success">快乐--</button>
  </form>
{% endblock %}

Week3_Simple_Search_Engine/mysearch/templates/index.html
{% extends 'base.html' %}

{% load highlight %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">肥宅快乐搜索器</a></li>
  <li class="breadcrumb-item active">index</li>
{% endblock %}

{% block content %}
  
  <a href="{% url 'home' %}">
  <button type="button" class="btn btn-success">Next Page</button></a>

  <div class="mb-4">
  </div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Title   (All={{num}})</th>
        <th>Id</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      {% for news in page %}

        <tr>
          <td>
          <a href="{% url 'get_details' news.cnt %}">{{news.title}}</a>
          <!--{% highlight news.contents with search html_tag "div" css_class "highlight_me_please" max_length 200 %}--> 
          </td>
          <td>{{ news.cnt }}</td>
          <td>{{ news.date }}</td>
        </tr>
      {% endfor %}
      {% for index in page.paginator.page_range %}

        {% if index == page.number %}
        <span><button type="button">{{index}}</button></a></span>
        {% else %}
        <a href="{% url 'index' index=index %}">
            <button type="button" >{{index}}</button></a>
        </a>
        {% endif %}

      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Week3_Simple_Search_Engine/mysearch/templates/info.html
{% extends 'base.html' %}

{% load highlight %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">肥宅快乐搜索器</a></li>
  <li class="breadcrumb-item active">{{ search }}</li>
{% endblock %}

{% block content %}
  
  <a href="{% url 'home' %}">
  <button type="button" class="btn btn-success">Next Page</button></a>

  <div class="mb-4">
  </div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Title  (All={{cntt}}  Time=={{time1}})</th>
        <th>Id</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      {% for news in page %}

        <tr>
          <td>
          <a href="{% url 'get_details' news.cnt %}">{% highlight news.title with search%}</a>
          <!--{% highlight news.contents with search html_tag "div" css_class "highlight_me_please" max_length 200 %}--> 
          <small class="text-muted d-block">{% highlight news.contents with search max_length 200 %}</small>
          </td>
          <td>{{ news.cnt }}</td>
          <td>{{ news.date }}</td>
        </tr>
      {% endfor %}
      {% for index in page.paginator.page_range %}

        {% if index == page.number %}
        <span><button type="button">{{index}}</button></a></span>
        {% else %}
        <a href="{% url 'info' index=index tsearch=tsearch %}">
            <button type="button" >{{index}}</button></a>
        </a>
        {% endif %}

      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Week3_Simple_Search_Engine/mysearch/templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_subject">Subject</label>
      <input type="text" class="form-control" id="id_subject" name="subject">
    </div>
    <div class="form-group">
      <label for="id_message">Message</label>
      <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
    </div>
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

Week3_Simple_Search_Engine/mysearch/templates/result.html
{% extends 'base.html' %}

{% load highlight %}

{% block title %}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">肥宅快乐搜索器</a></li>
  <li class="breadcrumb-item active">{{ search }}</li>
{% endblock %}

{% block content %}
  
  <a href="{% url 'home' %}">
  <button type="button" class="btn btn-success">Next Page</button></a>

  <div class="mb-4">
  </div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Title</th>
        <th>Id</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
      {% for news in results %}

        <tr>
          <td>
          <a href="{% url 'get_details' news.cnt %}">{% highlight news.title with search%}</a>
          <!--{% highlight news.contents with search html_tag "div" css_class "highlight_me_please" max_length 200 %}--> 
          <small class="text-muted d-block">{% highlight news.contents with search max_length 200 %}</small>
          </td>
          <td>{{ news.cnt }}</td>
          <td>{{ news.date }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

Week3_Simple_Search_Engine/mysearch/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
{% endblock %}

Week3_Simple_Search_Engine/mysearch/templates/topics.html
{% extends 'base.html' %}

{% block title %}
  {{ board.name }} - {{ block.super }}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">肥宅快乐搜索器</a></li>
  <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
  <div class="mb-4">
    <a href="{% url 'new_topic' board.pk %}" class="btn btn-primary">New topic</a>
  </div>
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Topic</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for topic in board.topics.all %}
        <tr>
          <td>{{ topic.subject }}</td>
          <td>{{ topic.starter.username }}</td>
          <td>0</td>
          <td>0</td>
          <td>{{ topic.last_updated }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}